version: '3'

services:
  postgres:
    image: docker.io/library/postgres:14
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks: ["pycher-network"]
    ports:
      - "5432:5432"

  redis:
    image: docker.io/library/redis:7-alpine
    command:
      [
        "redis-server",
        "--requirepass", "${REDIS_PASSWORD}",
        "--user", "${REDIS_USER}", "on", ">${REDIS_PASSWORD}", "~*", "+@all"
      ]
    environment:
      REDIS_USER: "${REDIS_USER}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    volumes: ["redis-data:/data"]
    networks: ["pycher-network"]
    ports:
      - "6379:6379"

  user-service:
    build: ./backend/user-service
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.development
    networks: ["pycher-network"]

  content-service:
    build: ./backend/content-service
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.development
    networks: ["pycher-network"]

  api-gateway:
    build:
      context: ./backend/api-gateway
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    networks: ["pycher-network"]
    depends_on:
      - user-service
      - content-service
      - execution-service
      - ai-service

  execution-service:
    build:
      context: ./backend/execution-service
    security_opt: ["no-new-privileges=true"]
    networks: ["pycher-network"]

  ai-service:
    build: ./backend/ai-service
    env_file:
      - .env.development
    networks: ["pycher-network"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks: ["pycher-network"]
    depends_on:
      - api-gateway

networks:
  pycher-network:
    driver: bridge

volumes:
  pg-data:
  redis-data:
