"""change name of field

Revision ID: 15cbd3e65919
Revises: 75df8ff22ef5
Create Date: 2025-05-29 16:11:12.841476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15cbd3e65919'
down_revision: Union[str, None] = '75df8ff22ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_submissions', sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('user_exercise_submissions', 'submission_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_submissions', sa.Column('submission_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('user_exercise_submissions', 'submitted_at')
    # ### end Alembic commands ###
