"""change name of field

Revision ID: 15cbd3e65919
Revises: 75df8ff22ef5
Create Date: 2025-05-29 16:11:12.841476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '15cbd3e65919'
down_revision: Union[str, None] = '75df8ff22ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(conn, table_name: str, column_name: str, schema: str = 'public') -> bool:
    """Checks if a column exists in a table."""
    sql = text(f"""
        SELECT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = :schema AND table_name = :table_name AND column_name = :column_name
        )
    """)
    return conn.execute(sql, {'schema': schema, 'table_name': table_name, 'column_name': column_name}).scalar_one()


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists(bind, 'user_exercise_submissions', 'submitted_at'):
        op.add_column('user_exercise_submissions', sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    if column_exists(bind, 'user_exercise_submissions', 'submission_at'):
        op.drop_column('user_exercise_submissions', 'submission_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists(bind, 'user_exercise_submissions', 'submission_at'):
        op.add_column('user_exercise_submissions', sa.Column('submission_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    if column_exists(bind, 'user_exercise_submissions', 'submitted_at'):
        op.drop_column('user_exercise_submissions', 'submitted_at')
    # ### end Alembic commands ###
