"""add uniqueness again

Revision ID: 2463bd472c8e
Revises: f26518a324a0
Create Date: 2025-06-23 11:41:50.673265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2463bd472c8e'
down_revision: Union[str, None] = 'f26518a324a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_unique_constraint('uq_user_lesson_progress', 'user_lesson_progress', ['user_id', 'lesson_id'])
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
