"""add_time

Revision ID: 2a04fdeff7cd
Revises: b3da0acefc5c
Create Date: 2025-06-02 19:45:10.521509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a04fdeff7cd'
down_revision: Union[str, None] = 'b3da0acefc5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('estimated_time_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'estimated_time_minutes')
    # ### end Alembic commands ###
