"""add_last_accessed_exercise_id_to_user_lesson_progress

Revision ID: 45ccc403761d
Revises: 5d8b23417d0d
Create Date: 2025-05-25 17:15:13.575422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ccc403761d'
down_revision: Union[str, None] = '5d8b23417d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_lesson_progress',
                  sa.Column('last_accessed_exercise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_user_lesson_progress_last_accessed_exercise_id_exercises', # Constraint name
        'user_lesson_progress', 'exercises', # Source table, referent table
        ['last_accessed_exercise_id'], ['id'] # Local columns, remote columns
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_lesson_progress_last_accessed_exercise_id_exercises', 'user_lesson_progress', type_='foreignkey')
    op.drop_column('user_lesson_progress', 'last_accessed_exercise_id')
    # ### end Alembic commands ###
