"""added exam tables

Revision ID: 55466fd216dd
Revises: 44a5ef4c3573
Create Date: 2025-06-13 21:56:26.928986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55466fd216dd'
down_revision: Union[str, None] = '44a5ef4c3573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_exams', sa.Column('time_limit_minutes', sa.Integer(), nullable=True))
    op.drop_column('course_exams', 'questions')
    op.drop_column('course_exams', 'order_index')
    op.add_column('user_course_enrollments', sa.Column('exam_unlocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_course_enrollments', 'exam_unlocked')
    op.add_column('course_exams', sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('course_exams', sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('course_exams', 'time_limit_minutes')
    # ### end Alembic commands ###
