"""new exam module

Revision ID: 56a69af77c45
Revises: 0884fcfa449e
Create Date: 2025-06-16 19:53:22.031485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '56a69af77c45'
down_revision: Union[str, None] = '0884fcfa449e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(conn, table_name: str, column_name: str, schema: str = 'public') -> bool:
    """Checks if a column exists in a table."""
    sql = text(f"""
        SELECT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = :schema AND table_name = :table_name AND column_name = :column_name
        )
    """)
    return conn.execute(sql, {'schema': schema, 'table_name': table_name, 'column_name': column_name}).scalar_one()


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists(bind, 'modules', 'is_exam'):
        op.add_column('modules', sa.Column('is_exam', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    if column_exists(bind, 'modules', 'is_exam'):
        op.drop_column('modules', 'is_exam')
    # ### end Alembic commands ###
