"""Restore is_correct column to UserExerciseSubmission

Revision ID: 6311b4ca5804
Revises: 8864d41e349c
Create Date: 2025-05-29 16:03:45.966549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6311b4ca5804'
down_revision: Union[str, None] = '8864d41e349c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_submissions', sa.Column('is_correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_exercise_submissions', 'is_correct')
    # ### end Alembic commands ###
