"""change name of fie;d

Revision ID: 75df8ff22ef5
Revises: 6311b4ca5804
Create Date: 2025-05-29 16:10:03.214207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75df8ff22ef5'
down_revision: Union[str, None] = '6311b4ca5804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_submissions', sa.Column('submission_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('user_exercise_submissions', 'submission_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_submissions', sa.Column('submission_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('user_exercise_submissions', 'submission_at')
    # ### end Alembic commands ###
