"""add explenation to exercises

Revision ID: 873420e24150
Revises: 2463bd472c8e
Create Date: 2025-06-29 14:45:22.897770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873420e24150'
down_revision: Union[str, None] = '2463bd472c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('explanation', sa.Text(), nullable=True))
    op.drop_constraint('uq_user_lesson_progress', 'user_lesson_progress', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_lesson_progress', 'user_lesson_progress', ['user_id', 'lesson_id'])
    op.drop_column('exercises', 'explanation')
    # ### end Alembic commands ###
