"""Add foreign key from user_exercise_submissions to users for user relationship

Revision ID: 8864d41e349c
Revises: da6813d14813
Create Date: 2025-05-29 15:23:01.614656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8864d41e349c'
down_revision: Union[str, None] = 'da6813d14813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_submissions', sa.Column('code_submitted', sa.Text(), nullable=False))
    op.add_column('user_exercise_submissions', sa.Column('passed', sa.Boolean(), nullable=True))
    op.add_column('user_exercise_submissions', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('user_exercise_submissions', sa.Column('submission_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_exercise_submissions', sa.Column('execution_time', sa.Float(), nullable=True))
    op.alter_column('user_exercise_submissions', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('user_exercise_submissions_user_progress_id_fkey', 'user_exercise_submissions', type_='foreignkey')
    op.drop_column('user_exercise_submissions', 'score')
    op.drop_column('user_exercise_submissions', 'attempt_number')
    op.drop_column('user_exercise_submissions', 'is_correct')
    op.drop_column('user_exercise_submissions', 'execution_time_ms')
    op.drop_column('user_exercise_submissions', 'submitted_at')
    op.drop_column('user_exercise_submissions', 'user_progress_id')
    op.drop_column('user_exercise_submissions', 'submitted_code')
    op.create_foreign_key(None, 'user_lesson_progress', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_lesson_progress', type_='foreignkey')
    op.add_column('user_exercise_submissions', sa.Column('submitted_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_exercise_submissions', sa.Column('user_progress_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_exercise_submissions', sa.Column('submitted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('user_exercise_submissions', sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_exercise_submissions', sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user_exercise_submissions', sa.Column('attempt_number', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('user_exercise_submissions', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_exercise_submissions_user_progress_id_fkey', 'user_exercise_submissions', 'user_progress', ['user_progress_id'], ['id'])
    op.alter_column('user_exercise_submissions', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_exercise_submissions', 'execution_time')
    op.drop_column('user_exercise_submissions', 'submission_date')
    op.drop_column('user_exercise_submissions', 'error_message')
    op.drop_column('user_exercise_submissions', 'passed')
    op.drop_column('user_exercise_submissions', 'code_submitted')
    # ### end Alembic commands ###
