"""diosmio ya

Revision ID: 901030a37341
Revises: a6b4a3078af1
Create Date: 2025-06-04 09:50:22.968003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '901030a37341'
down_revision: Union[str, None] = 'a6b4a3078af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_module_progress', 'user_module_progress', ['user_id', 'module_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_module_progress', 'user_module_progress', type_='unique')
    # ### end Alembic commands ###
