"""added order_index to course_exam

Revision ID: aebe0fd503a5
Revises: 9c12f7a2501e
Create Date: 2025-06-22 15:08:11.651405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebe0fd503a5'
down_revision: Union[str, None] = '9c12f7a2501e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_exams', sa.Column('order_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_lesson_progress', 'user_lesson_progress', ['user_id', 'lesson_id'])
    op.drop_column('course_exams', 'order_index')
    # ### end Alembic commands ###
