"""add_feedback_to_user_exercise_submissions

Revision ID: cf36296cfcaa
Revises: df13caae0fac
Create Date: 2025-06-02 19:32:50.007636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf36296cfcaa'
down_revision: Union[str, None] = 'df13caae0fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_submissions', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_exercise_submissions', 'feedback')
    # ### end Alembic commands ###
