"""added_is_unlocked

Revision ID: d0887f6625a7
Revises: 901030a37341
Create Date: 2025-06-04 16:58:57.419218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0887f6625a7'
down_revision: Union[str, None] = '901030a37341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_module_progress', sa.Column('is_unlocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_module_progress', 'is_unlocked')
    # ### end Alembic commands ###
