"""Modify Exercise table for dynamic validation: remove solution_code, test_cases; add validation_type, validation_rules

Revision ID: da6813d14813
Revises: f386dfb619d3
Create Date: 2025-05-29 14:50:47.697524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'da6813d14813'
down_revision: Union[str, None] = 'f386dfb619d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
     # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('validation_type', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('exercises', 'solution_code')
    op.drop_column('exercises', 'test_cases')


def downgrade() -> None:
     # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('test_cases', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('solution_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('exercises', 'validation_rules')
    op.drop_column('exercises', 'validation_type')
