"""dios mio ya

Revision ID: df13caae0fac
Revises: 15cbd3e65919
Create Date: 2025-05-29 18:58:49.061348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df13caae0fac'
down_revision: Union[str, None] = '15cbd3e65919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_submissions', sa.Column('attempt_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_exercise_submissions', 'attempt_number')
    # ### end Alembic commands ###
