"""add uniqueness to lesson progress

Revision ID: e40d324db272
Revises: 873420e24150
Create Date: 2025-06-29 20:51:04.107046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40d324db272'
down_revision: Union[str, None] = '873420e24150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- ADD THIS BLOCK TO DELETE DUPLICATES ---
    # This SQL statement finds rows with the same user_id and lesson_id,
    # and deletes all but the one with the highest ID (the most recent entry).
    op.execute("""
        DELETE FROM user_lesson_progress a
        USING user_lesson_progress b
        WHERE a.id < b.id
        AND a.user_id = b.user_id
        AND a.lesson_id = b.lesson_id;
    """)
    # --- END OF BLOCK TO ADD ---

    op.create_unique_constraint('uq_user_lesson_progress', 'user_lesson_progress', ['user_id', 'lesson_id'])
    # ... other auto-generated commands will be here ...
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
