"""add is_Active course enrollments

Revision ID: edf047a461e3
Revises: 59eced616f19
Create Date: 2025-07-08 18:22:27.002122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf047a461e3'
down_revision: Union[str, None] = '59eced616f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_course_enrollments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('fk_user_lesson_progress_user_id'), 'user_lesson_progress', type_='foreignkey')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.create_foreign_key(op.f('fk_user_lesson_progress_user_id'), 'user_lesson_progress', 'users', ['user_id'], ['id'])
    op.drop_column('user_course_enrollments', 'is_active')
    # ### end Alembic commands ###
