"""add failure count to user exam attempts

Revision ID: f26518a324a0
Revises: aebe0fd503a5
Create Date: 2025-06-23 10:44:18.436433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26518a324a0'
down_revision: Union[str, None] = 'aebe0fd503a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exam_attempts', sa.Column('course_id', sa.Integer(), nullable=False))
    op.add_column('user_exam_attempts', sa.Column('exercise_id', sa.Integer(), nullable=False))
    op.add_column('user_exam_attempts', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user_exam_attempts', sa.Column('failure_count', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_exam_attempts', 'exercises', ['exercise_id'], ['id'])
    op.create_foreign_key(None, 'user_exam_attempts', 'courses', ['course_id'], ['id'])
    op.drop_constraint('uq_user_lesson_progress', 'user_lesson_progress', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_lesson_progress', 'user_lesson_progress', ['user_id', 'lesson_id'])
    op.drop_constraint(None, 'user_exam_attempts', type_='foreignkey')
    op.drop_constraint(None, 'user_exam_attempts', type_='foreignkey')
    op.drop_column('user_exam_attempts', 'failure_count')
    op.drop_column('user_exam_attempts', 'is_active')
    op.drop_column('user_exam_attempts', 'exercise_id')
    op.drop_column('user_exam_attempts', 'course_id')
    # ### end Alembic commands ###
