"""add_user_progress_id_to_user_exercise_submissions

Revision ID: f386dfb619d3
Revises: c02851b573fd
Create Date: 2025-05-28 18:27:28.630836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f386dfb619d3'
down_revision: Union[str, None] = 'c02851b573fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_submissions', sa.Column('user_progress_id', sa.Integer(), nullable=True))
    op.alter_column('user_exercise_submissions', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_exercise_submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_user_exercise_submissions_lesson_id', table_name='user_exercise_submissions')
    op.create_foreign_key(None, 'user_exercise_submissions', 'user_progress', ['user_progress_id'], ['id'])
    op.create_foreign_key(None, 'user_exercise_submissions', 'users', ['user_id'], ['id'])
    op.drop_column('user_exercise_submissions', 'attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_submissions', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_exercise_submissions', type_='foreignkey')
    op.drop_constraint(None, 'user_exercise_submissions', type_='foreignkey')
    op.create_index('ix_user_exercise_submissions_lesson_id', 'user_exercise_submissions', ['lesson_id'], unique=False)
    op.alter_column('user_exercise_submissions', 'submitted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_exercise_submissions', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('user_exercise_submissions', 'user_progress_id')
    # ### end Alembic commands ###
